import React from 'react';
import '../Styles/weekblog.css'
import ArrowCircleRightIcon from '@mui/icons-material/ArrowCircleRight';
import ArrowCircleLeftIcon from '@mui/icons-material/ArrowCircleLeft';
import { Link } from 'react-router-dom';
function WeekThree() {
  return (
    <div>
      <h1>Road to the Finishing Line</h1>
      <p className="date">Posted on June 20, 2023</p>
      <main>
        <section className="blog-content">
          <img src="https://thumbs.dreamstime.com/b/asphalt-road-finish-line-message-107117082.jpg" alt="Photo of road to finish line" />
          <p>During the final processes of my internet art project, I embarked on a meticulous process of contemplating its integration into my website as a whole. My primary goal was to seamlessly merge my internet art with the rest of the website's content. It occurred to me that I could achieve this by focusing on the beauty that emerges from the chaos experienced by students. After much contemplation, a realization struck me: many of the challenges students face are either personal or school-related, and screens or monitors often play a significant role in dealing with those challenges. </p>

          <p>This realization became the driving force behind my concept, as I aimed to immerse users in the mindset of a student by surrounding the entire website with a monitor. In addition, I included a background that I found on Pinterest, a study area background. By incorporating the study background, the website establishes a relatable connection with its target audience, symbolizing a safe and familiar space where students spend countless hours studying and pursuing their educational goals. This design choice creates an emotional resonance and invites users, especially female students, to explore the website and engage with its content more deeply. By doing so, users themselves become the students, forging a powerful connection with the internet art. This integration perfectly aligned with my use of Reddit as an API to retrieve relevant content. It allowed users to experience the beauty and chaos that students worldwide encounter on a daily basis.</p>

          <p>To execute this vision, I implemented two distinct tabs in the Internet Art page: one focused on chaos and another on beauty. The chaos tab was designed to resemble a community forum where individuals could share their student-related or life problems, creating a sense of relatability. This section of the website was filled with posts from users expressing their frustrations as students or young adults. It aimed to capture the essence of shared problems, highlighting the fact that we all face challenges in life.</p>

          <p>Conversely, the beauty tab was designed to showcase the transformative power of finding beauty within chaos. It featured memes created by students, providing a light-hearted and humorous atmosphere. This section offered users a breath of fresh air, allowing them to escape from the overwhelming problems and immerse themselves in the beauty generated by their fellow students.</p>

          <p>To enhance user interaction, I incorporated the ability to like or dislike memes and posts. This feature allowed users to engage with the content, expressing their resonance or lack thereof with specific pieces. It fostered a sense of involvement and personalization, making the internet art experience more immersive and engaging. However, despite my efforts, there was one aspect of the project that I was unable to complete successfully—the message bar. The original plan was to create a platform where users could type and submit their own comments, replicating a community atmosphere where individuals could share the chaos in their lives. Unfortunately, despite numerous attempts, extensive research, and seeking assistance on forums, I was unable to resolve the issue. Thus, I acknowledge that this objective remained unfulfilled, and I cannot claim complete success in realizing my vision for the internet art.</p>

          <p>Nevertheless, I view my endeavour as a significant step forward. The presence of the monitor throughout the website created a seamless integration between the internet art and the overall experience. It successfully captured the essence of student chaos and highlighted the beauty that emerges from it. The project fostered a sense of community, allowing users to connect with the challenges faced by students globally. Overall, while I acknowledge the limitations and the unfinished aspect of the message bar, I consider it a commendable attempt that effectively tied my internet art to the broader themes explored on my website.</p>

          
        </section>

        <section className="button-container-bottom">
          <Link to = "/UIXTwo">
            <button className="button button-left-bottom">
              <ArrowCircleLeftIcon/> Previous
            </button>
            </Link>          
            <Link to = "/End">
            <button className="button button-right-bottom">
              Next <ArrowCircleRightIcon/>
            </button>
            </Link>       
             </section>
      </main>
    </div>
  );
}

export default WeekThree;
