import React from 'react';
import '../Styles/weekblog.css'
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import ArrowCircleRightIcon from '@mui/icons-material/ArrowCircleRight';
import ArrowCircleLeftIcon from '@mui/icons-material/ArrowCircleLeft';
import { Link } from 'react-router-dom';


function Week5Theory() {
  return (
    <div>
      <h1>The rise of the new era of Art</h1>
      <p className="date">Posted on April 15, 2023</p>
      <main>
        <section className="blog-content">
          <img src="https://d7hftxdivxxvm.cloudfront.net/?height=320&quality=80&resize_to=fill&src=https%3A%2F%2Fartsy-media-uploads.s3.amazonaws.com%2FUnBKLp38kHJrYoEU-FfXsw%252Fheaderfinal.jpg&width=767" alt="Photo of an example of internet art" />
          <p>The rise of the internet and digital technology has brought about a new era of art. This art, known as internet art or net art, takes advantage of the internet as a medium, allowing artists to create works that are not only interactive but also accessible to anyone with an internet connection. In this paper, we will critically reflect on four articles about internet art and gain insight by tying them all together.</p>
          <p>The first article, "10 Artistic Masterpieces Meant to be Experienced Online" by Molly Gottschalk on Artsy, discusses how artists are using the internet as a medium to create works that are meant to be experienced online. The article showcases ten examples of internet-based art, including Olia Lialina's "My Boyfriend Came Back From The War," (seen below) which uses hyperlinks to tell a story, and Jon Rafman's "9-Eyes," a collection of images found on Google Street View. This article focuses on the idea of art that is specifically designed to be experienced online. The pieces discussed range from interactive web-based projects to digital collages and animations. One interesting point made in the article is that online art can often be more accessible to a wider audience than traditional art forms, as it is not bound by physical location. This raises questions about the democratization of art and who gets to define what is and isn't "art." Another important aspect of online art highlighted in the article is its potential for interactivity, allowing viewers to engage with the work in new and exciting ways.</p>

          <img src="https://d7hftxdivxxvm.cloudfront.net/?height=601&quality=80&resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FNjM4Mm7aoIVmqGV3LeOB8w%2Fnormalized.jpg&width=800" alt="Photo of Olia's Lialina's work " />

          <p>The second article, "Agents of Change: Internet & Net Art - How the World Wide Web has Affected the Way We Make Art" by Charlotte Jansen on Artland Magazine, explores the history and impact of net art. The article discusses how early net artists used the internet as a platform to challenge traditional art world hierarchies and how contemporary artists are still using the internet to explore new forms and ideas. One key point made in the article is that net art is often highly political, as it provides a platform for artists to critique and subvert dominant power structures.</p>
          <p>The third article, "The New Museum Hits Save on Net Art" by Allison Meier on Hyperallergic, reports on the New Museum's efforts to archive and preserve net art. The article discusses how the museum's "Net Art Anthology" project seeks to document the history of net art and make it accessible to a wider audience. focuses on the efforts of the New Museum in New York City to preserve and archive net art for future generations. It highlights the challenges of preserving digital art, which can be easily lost or corrupted over time. The article argues that the preservation of net art is crucial, both for its historical significance and as a means of understanding the ongoing evolution of the internet and digital culture.</p>
          <p>The fourth article, "ICA Opens First Major US Exhibition to Examine the Impact of the Internet on Visual Art" by Sarah Cascone on the Institute of Contemporary Art (ICA) Boston's website, discusses the ICA's exhibition "Art in the Age of the Internet, 1989 to Today." The exhibition explores how the internet has influenced art since its inception and features works by artists who use the internet as a medium or subject matter. The exhibition also includes works that address issues such as surveillance, privacy, and identity in the digital age. The exhibition features a wide range of works, including sculpture, video, and installation, all of which engage with digital technology in some way. One interesting point made in the article is that many of the works in the exhibition are not explicitly "about" the internet, but instead use digital tools as a means of exploring broader themes and ideas.</p>
          <p>In terms of commonalities amongst these articles, several key themes emerge. One is the idea of the internet as a democratizing force in the world of art, providing new opportunities for artists to connect with audiences and engage with a wider range of perspectives. The internet has been a transformative force for the world of art, providing a platform for artists to showcase their work and connect with audiences from around the world. Prior to the widespread adoption of the internet, artists were often limited by the reach of their physical galleries and exhibitions. However, with the advent of online platforms, artists now have the ability to share their work with a global audience at the click of a button.</p>
          <p>One of the keyways in which the internet has democratized the world of art is by providing new opportunities for artists to connect with audiences and engage with a wider range of perspectives. Social media platforms like Instagram, Twitter, and TikTok have enabled artists to showcase their work to millions of users around the world, allowing them to reach a far wider audience than would have been possible through traditional means. Additionally, these platforms have made it easier for artists to connect with other creatives and collaborate on projects, breaking down the barriers that once existed between different artistic communities.</p>
          <p>Another way in which the internet has democratized the world of art is by providing new opportunities for artists to create and distribute their work. With the rise of digital tools and platforms, artists now have access to a wider range of creative tools than ever before. From digital painting and 3D modelling software to online marketplaces and crowdfunding platforms, the internet has provided artists with new ways to create, distribute, and sell their work. Furthermore, the internet has also allowed for greater diversity and inclusivity within the art world. By providing a platform for artists from marginalized communities to share their work, the internet has helped to break down some of the systemic barriers that have long existed within the art world. In this way, the internet has become a powerful tool for promoting social justice and empowering artists from all backgrounds to share their unique perspectives with the world.</p>
          <p>Another theme is the political potential of net art, which often challenges dominant power structures and subverts traditional hierarchies. One of the key features of net art is its ability to empower artists and activists, who can create content and distribute it with ease on various platforms. This has led to the emergence of new voices and perspectives, challenging established narratives and giving voice to marginalized communities. For instance, the #MeToo movement, which began as a social media campaign, demonstrated the power of the internet to amplify the voices of survivors of sexual harassment and assault.</p>
          <p>In addition, net art often challenges traditional hierarchies and power structures. By using technology to create new forms of expression, net artists can bypass the gatekeepers of the traditional art world and present their work to a wider audience. This can be particularly significant for artists from marginalized communities, who may face barriers to entry in the traditional art world due to factors such as race, gender, or socioeconomic status.</p>
          <p>Moreover, net art can offer a platform for political dissent and activism, particularly in repressive regimes where traditional forms of protest are curtailed. For instance, during the Arab Spring uprisings in 2011, net art played a significant role in mobilizing protesters and challenging the authoritarian regimes in Egypt, Tunisia, and Libya. Similarly, net art has been used to protest against police brutality and racial injustice in the United States and other countries.</p>
          <p>However, the political potential of net art is not without its challenges. The internet is a vast and often chaotic space, and it can be difficult to make one's voice heard amidst the cacophony of competing messages. In addition, net art can also be subject to censorship and surveillance by governments and other powerful entities, which can limit its potential as a tool for political dissent.</p>
          <p>A third theme is the importance of preserving digital art, both for its historical significance and as a means of understanding the ongoing evolution of digital culture. In terms of preserving internet art, it poses unique challenges compared to traditional art forms. The ephemeral nature of the internet and the rapid pace of technological advancement make it difficult to preserve internet art. Additionally, internet art often utilizes platforms and technologies that become obsolete over time, making it challenging to access and experience the artwork in its original form.</p>
          <p>One approach to preserving internet art is through documentation and archiving. By creating a record of the artwork through screenshots, videos, and other digital media, we can ensure that the artwork is accessible even if the original platform or technology becomes obsolete. Another approach is to create emulations or recreations of the artwork using current technologies, allowing audiences to experience the artwork as intended.</p>
          <p>It is also crucial for institutions and collectors to invest in the preservation of internet art. This can be done by developing new technologies and methods for preserving digital art and by providing support for artists working in this field.</p>
          <p>Overall, these articles highlight the ongoing impact of the internet on the world of art, and the ways in which artists are continually pushing the boundaries of what is possible in the digital age.</p>
        </section>

        <section className="button-container-bottom">
          <Link to = "/Week5">
            <button className="button button-left-bottom">
              <ArrowCircleLeftIcon/> Previous
            </button>
            </Link>          
            <Link to = "/Week6">
            <button className="button button-right-bottom">
              Next <ArrowCircleRightIcon/>
            </button>
            </Link>       
             </section>
      </main>
    </div>
  );
}

export default Week5Theory;
